# Generated by Django 3.1.3 on 2020-11-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crepe_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crepe',
            name='crepe_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
