# Generated by Django 3.1.3 on 2020-11-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crepe_app', '0002_auto_20201128_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crepe',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='side',
            name='price',
            field=models.FloatField(),
        ),
    ]
