# Generated by Django 3.1.3 on 2020-12-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crepe_app', '0003_auto_20201129_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='group',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beverage',
            name='limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fruit',
            name='group',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fruit',
            name='limit',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nut',
            name='group',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nut',
            name='limit',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='side',
            name='group',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='side',
            name='limit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topping',
            name='group',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topping',
            name='limit',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrap',
            name='group',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrap',
            name='limit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
